{
  "products": [
    {
      "id": "FLM_80118",
      "name": "Varazdin Orchestral",
      "link": "com.imageline.flstudiomobilehd.vrz",
      "category": "Samples",
      "version": "3.3.0",
      "filename": "FLM3 Varazdin Orchestral flac.zip",
      "free": true,
      "owned": true,
      "description": "A mini orchestra at your fingertips",
      "image": "https://support.image-line.com/images/product/Varazdin Orchestral.png",
      "weight": "40",
      "demo": "https://support.image-line.com/innovaeditor/assets/plugins/audio/Varazdin Orchestral FL Studio Mobile Expansion.mp3",
      "download": "https://streamermobile.image-line.com/inappv3/downloadProduct.php?hash=d32e9502c32600a8f0d45f0051c2ea79&version=&productname=com.imageline.flstudiomobilehd.vrz&time=1670783184",
      "formats": "",
      "genre": "",
      "instrument": "Orchestral;String",
      "plugin": "Instruments"
    },
    {
      "id": "FLM_80105",
      "name": "Sliced Beats",
      "link": "com.imageline.flstudiomobilehd.slicedbeats",
      "category": "Samples",
      "version": "3.6.0",
      "filename": "FLM3 Sliced Beats flac for 3.6.zip",
      "free": true,
      "owned": true,
      "description": "25 Funky chopped beats ready to roll in your projects (Slicer)",
      "image": "https://support.image-line.com/images/product/Sliced Beats.png",
      "weight": "70",
      "demo": "https://support.image-line.com/innovaeditor/assets/plugins/audio/Sliced Beats FL Studio Mobile Expansion.mp3",
      "download": "https://streamermobile.image-line.com/inappv3/downloadProduct.php?hash=d32e9502c32600a8f0d45f0051c2ea79&version=&productname=com.imageline.flstudiomobilehd.slicedbeats&time=1670783184",
      "formats": "DirectWave,Loop Samples",
      "genre": "",
      "instrument": "Drum",
      "plugin": "Loops"
    },
    {
      "id": "FLM_AMPED",
      "name": "Amped Bass & Guitars",
      "link": "com.imageline.flstudiomobilehd.amped",
      "category": "Samples",
      "version": "3.3.0",
      "filename": "FLM3 Amped Guitars flac.zip",
      "free": false,
      "owned": false,
      "description": "Classic electric and acoustic guitar and bass instruments",
      "image": "https://support.image-line.com/images/product/Amped.png",
      "weight": "8",
      "demo": "https://support.image-line.com/innovaeditor/assets/plugins/audio/Amped FL Studio Mobile Expansion.mp3",
      "download": "https://streamermobile.image-line.com/inappv3/downloadProduct.php?hash=d32e9502c32600a8f0d45f0051c2ea79&version=&productname=com.imageline.flstudiomobilehd.amped&time=1670783184",
      "formats": "",
      "genre": "",
      "instrument": "Guitar",
      "plugin": "Instruments"
    },
    {
      "id": "FLM_DRUMAXX",
      "name": "Drumaxx",
      "link": "com.imageline.flstudiomobilehd.drumaxx",
      "category": "Samples",
      "version": "3.6.0",
      "filename": "FLM3 Drumaxx flac for 3.6.zip",
      "free": true,
      "owned": true,
      "description": "Drum sounds sampled from Drumaxx physical modelling",
      "image": "https://support.image-line.com/images/product/FLM Drumaxx.png",
      "weight": "75",
      "demo": "https://support.image-line.com/innovaeditor/assets/plugins/audio/Drumaxx FL Studio Mobile Expansion.mp3",
      "download": "https://streamermobile.image-line.com/inappv3/downloadProduct.php?hash=d32e9502c32600a8f0d45f0051c2ea79&version=&productname=com.imageline.flstudiomobilehd.drumaxx&time=1670783184",
      "formats": "DirectWave,Loop Samples",
      "genre": "",
      "instrument": "Drum",
      "plugin": "Loops"
    },
    {
      "id": "FLM_SFX",
      "name": "SFX",
      "link": "com.imageline.flstudiomobilehd.sfx",
      "category": "Samples",
      "version": "3.3.0",
      "filename": "FLM3 SFX flac.zip",
      "free": true,
      "owned": true,
      "description": "A pallet of sound effects, noises and speech",
      "image": "https://support.image-line.com/images/product/FLM SFX.png",
      "weight": "95",
      "demo": "https://support.image-line.com/innovaeditor/assets/plugins/audio/SFX FL Studio Mobile Expansion.mp3",
      "download": "https://streamermobile.image-line.com/inappv3/downloadProduct.php?hash=d32e9502c32600a8f0d45f0051c2ea79&version=&productname=com.imageline.flstudiomobilehd.sfx&time=1670783184",
      "formats": "",
      "genre": "",
      "instrument": "SFX",
      "plugin": "Instruments"
    },
    {
      "id": "FLM_SYNTHBASS",
      "name": "Synth Bass",
      "link": "com.imageline.flstudiomobilehd.synthbass",
      "category": "Samples",
      "version": "3.3.0",
      "filename": "FLM3 Synth Bass flac.zip",
      "free": true,
      "owned": true,
      "description": "A source of synthesized bass instruments",
      "image": "https://support.image-line.com/images/product/Synth Bass.png",
      "weight": "36",
      "demo": "https://support.image-line.com/innovaeditor/assets/plugins/audio/Synth Bass FL Studio Mobile Expansion.mp3",
      "download": "https://streamermobile.image-line.com/inappv3/downloadProduct.php?hash=d32e9502c32600a8f0d45f0051c2ea79&version=&productname=com.imageline.flstudiomobilehd.synthbass&time=1670783184",
      "formats": "",
      "genre": "",
      "instrument": "Bass;Synth",
      "plugin": "Instruments"
    },
    {
      "id": "FLM_SYNTHLEAD",
      "name": "Synth Lead",
      "link": "com.imageline.flstudiomobilehd.synthlead",
      "category": "Samples",
      "version": "3.3.0",
      "filename": "FLM3 Synth Lead flac.zip",
      "free": false,
      "owned": false,
      "description": "Lead synth instruments for the core of your projects",
      "image": "https://support.image-line.com/images/product/Synth Lead.png",
      "weight": "80",
      "demo": "https://support.image-line.com/innovaeditor/assets/plugins/audio/Synth Lead FL Studio Mobile Expansion.mp3",
      "download": "https://streamermobile.image-line.com/inappv3/downloadProduct.php?hash=d32e9502c32600a8f0d45f0051c2ea79&version=&productname=com.imageline.flstudiomobilehd.synthlead&time=1670783184",
      "formats": "",
      "genre": "",
      "instrument": "Synth",
      "plugin": "Instruments"
    },
    {
      "id": "FLM_ACOUGUIT",
      "name": "Acoustic Guitar",
      "link": "com.imageline.flstudiomobilehd.acouguit",
      "category": "Samples",
      "version": "3.3.0",
      "filename": "FLM3 Acoustic Guitars flac.zip",
      "free": false,
      "owned": false,
      "description": "Warm acoustic guitar instruments to pluck and strum",
      "image": "https://support.image-line.com/images/product/Acoustic Guitar.png",
      "weight": "30",
      "demo": "https://support.image-line.com/innovaeditor/assets/plugins/audio/Acoustic Guitar FL Studio Mobile Expansion.mp3",
      "download": "https://streamermobile.image-line.com/inappv3/downloadProduct.php?hash=d32e9502c32600a8f0d45f0051c2ea79&version=&productname=com.imageline.flstudiomobilehd.acouguit&time=1670783184",
      "formats": "",
      "genre": "",
      "instrument": "Guitar",
      "plugin": "Instruments"
    },
    {
      "id": "FLM_VOICES",
      "name": "Voices",
      "link": "com.imageline.flstudiomobilehd.voices",
      "category": "Samples",
      "version": "3.3.0",
      "filename": "FLM3 Voices flac.zip",
      "free": false,
      "owned": false,
      "description": "Resynthesized acapella vocal samples",
      "image": "https://support.image-line.com/images/product/FLM Voices EXP.png",
      "weight": "65",
      "demo": "https://support.image-line.com/innovaeditor/assets/plugins/audio/Voices FL Studio Mobile Expansion.mp3",
      "download": "https://streamermobile.image-line.com/inappv3/downloadProduct.php?hash=d32e9502c32600a8f0d45f0051c2ea79&version=&productname=com.imageline.flstudiomobilehd.voices&time=1670783184",
      "formats": "",
      "genre": "",
      "instrument": "Vocal",
      "plugin": "Instruments"
    },
    {
      "id": "FLM_TR808",
      "name": "Tuned 808 Bass",
      "link": "com.imageline.flstudiomobilehd.tr808",
      "category": "Samples",
      "version": "3.3.0",
      "filename": "FLM3 Tuned 808 Bass flac.zip",
      "free": false,
      "owned": false,
      "description": "25 processed and sustained 808 samples to play melodically",
      "image": "https://support.image-line.com/images/product/Tuned 808 Bass.png",
      "weight": "46",
      "demo": "https://support.image-line.com/innovaeditor/assets/plugins/audio/Tuned 808 Bass FL Studio Mobile Expansion.mp3",
      "download": "https://streamermobile.image-line.com/inappv3/downloadProduct.php?hash=d32e9502c32600a8f0d45f0051c2ea79&version=&productname=com.imageline.flstudiomobilehd.tr808&time=1670783184",
      "formats": "",
      "genre": "",
      "instrument": "Bass",
      "plugin": "Instruments"
    },
    {
      "id": "FLM_SYNTHPLUCK",
      "name": "Synth Pluck",
      "link": "com.imageline.flstudiomobilehd.synthpluck",
      "category": "Samples",
      "version": "3.3.0",
      "filename": "FLM3 Synth Pluck flac.zip",
      "free": false,
      "owned": false,
      "description": "35 Plucked Synths to use as leads, arps or basses",
      "image": "https://support.image-line.com/images/product/FLM Synth Pluck EXP.png",
      "weight": "90",
      "demo": "https://support.image-line.com/innovaeditor/assets/plugins/audio/Synth Pluck FL Studio Mobile Expansion.mp3",
      "download": "https://streamermobile.image-line.com/inappv3/downloadProduct.php?hash=d32e9502c32600a8f0d45f0051c2ea79&version=&productname=com.imageline.flstudiomobilehd.synthpluck&time=1670783184",
      "formats": "",
      "genre": "",
      "instrument": "Synth",
      "plugin": "Instruments"
    },
    {
      "id": "FLM_ESSENTIALPIANOS",
      "name": "Essential Pianos",
      "link": "com.imageline.flstudiomobilehd.essentialpianos",
      "category": "Bundle offer",
      "version": "3.3.0",
      "filename": "FLM3 Essential Pianos flac.zip",
      "free": true,
      "owned": false,
      "description": "12 Beautifully multisampled acoustic and electric Pianos",
      "image": "https://support.image-line.com/images/product/flm_essential_pianos_2.png",
      "weight": "50",
      "demo": "https://support.image-line.com/innovaeditor/assets/plugins/audio/essential_pianos_fl_studio_mobile_expansion_3.mp3",
      "download": "https://streamermobile.image-line.com/inappv3/downloadProduct.php?hash=d32e9502c32600a8f0d45f0051c2ea79&version=&productname=com.imageline.flstudiomobilehd.essentialpianos&time=1670783184",
      "formats": "",
      "genre": "",
      "instrument": "Piano",
      "plugin": "Instruments"
    },
    {
      "id": "FLM_DRUMFULTREASURE",
      "name": "Drumful Treasure",
      "link": "com.imageline.flstudiomobilehd.drumfultreasure",
      "category": "Bundle offer",
      "version": "3.3.0",
      "filename": "FLM3 Drumful Treasure flac.zip",
      "free": true,
      "owned": false,
      "description": "500 Expertly crafted electronic drum samples",
      "image": "https://support.image-line.com/images/product/flm_drumful_treasure_2.png",
      "weight": "45",
      "demo": "https://support.image-line.com/innovaeditor/assets/plugins/audio/drumful_treasure_fl_studio_mobile_expansion_3.mp3",
      "download": "https://streamermobile.image-line.com/inappv3/downloadProduct.php?hash=d32e9502c32600a8f0d45f0051c2ea79&version=&productname=com.imageline.flstudiomobilehd.drumfultreasure&time=1670783184",
      "formats": "DirectWave,Drum Samples",
      "genre": "",
      "instrument": "Drum",
      "plugin": "Instruments;Samples"
    },
    {
      "id": "FLM_OLDSCHOOLBREAKBEATS",
      "name": "Oldschool Breakbeats",
      "link": "com.imageline.flstudiomobilehd.oldschoolbreakbeats",
      "category": "Bundle offer",
      "version": "3.6.0",
      "filename": "FLM3 Oldschool Breakbeats flac for 3.6.zip",
      "free": false,
      "owned": false,
      "description": "56 Classic sounding drum breaks (Slicer)",
      "image": "https://support.image-line.com/images/product/Oldschool-Breakbeats-FLM.png",
      "weight": "23",
      "demo": "https://support.image-line.com/innovaeditor/assets/plugins/audio/Oldschool Breakbeats FL Studio Mobile Expansion.mp3",
      "download": "https://streamermobile.image-line.com/inappv3/downloadProduct.php?hash=d32e9502c32600a8f0d45f0051c2ea79&version=&productname=com.imageline.flstudiomobilehd.oldschoolbreakbeats&time=1670783184",
      "formats": "Loop Samples",
      "genre": "",
      "instrument": "Drum",
      "plugin": "Loops"
    },
    {
      "id": "FLM_SLICEDSYNTHSEQUENCES",
      "name": "Sliced Synth Sequences",
      "link": "com.imageline.flstudiomobilehd.slicedsynthsequences",
      "category": "Bundle offer",
      "version": "3.6.0",
      "filename": "FLM3 Sliced Synth Sequences.zip",
      "free": false,
      "owned": false,
      "description": "500 Sliced melodic sequences synthesized in C Minor (Slicer)",
      "image": "https://support.image-line.com/images/product/FLM sliced-synth-sequences.png",
      "weight": "20",
      "demo": "https://support.image-line.com/innovaeditor/assets/plugins/audio/sliced_synth_sequences_fl_studio_mobile_expansion_demo.mp3",
      "download": "https://streamermobile.image-line.com/inappv3/downloadProduct.php?hash=d32e9502c32600a8f0d45f0051c2ea79&version=&productname=com.imageline.flstudiomobilehd.slicedsynthsequences&time=1670783184",
      "formats": "Loop Samples",
      "genre": "",
      "instrument": "Synth",
      "plugin": "Loops"
    },
    {
      "id": "FLM_SYNTHETIXBEATS",
      "name": "Synthetix Beats",
      "link": "com.imageline.flstudiomobilehd.synthetixbeats",
      "category": "Bundle offer",
      "version": "3.6.0",
      "filename": "FLM3 Synthetix Beats.zip",
      "free": false,
      "owned": false,
      "description": "500 Electronic drum loops synthesized in another world (Slicer)",
      "image": "https://support.image-line.com/images/product/FLM synthetix-beats.png",
      "weight": "25",
      "demo": "https://support.image-line.com/innovaeditor/assets/plugins/audio/synthetix_beats_fl_studio_mobile_expansion_demo.mp3",
      "download": "https://streamermobile.image-line.com/inappv3/downloadProduct.php?hash=d32e9502c32600a8f0d45f0051c2ea79&version=&productname=com.imageline.flstudiomobilehd.synthetixbeats&time=1670783184",
      "formats": "Loop Samples",
      "genre": "",
      "instrument": "Drum",
      "plugin": "Loops"
    },
    {
      "id": "FLM_PSYTRANCE",
      "name": "PsyTrance",
      "link": "com.imageline.flstudiomobilehd.psytrance",
      "category": "Bundle offer",
      "version": "3.6.0",
      "filename": "FLM3 PsyTrance flac.zip",
      "free": false,
      "owned": false,
      "description": "30 Presets and 200 samples to make PsyTrance from scratch!",
      "image": "https://support.image-line.com/images/product/flm-psytrance.png",
      "weight": "100",
      "demo": "https://support.image-line.com/innovaeditor/assets/plugins/audio/flm-psytrance-demo.mp3",
      "download": "https://streamermobile.image-line.com/inappv3/downloadProduct.php?hash=d32e9502c32600a8f0d45f0051c2ea79&version=&productname=com.imageline.flstudiomobilehd.psytrance&time=1670783184",
      "formats": "DirectWave,Drum Samples",
      "genre": "",
      "instrument": "Bass;Synth;SFX;Drum",
      "plugin": "Instruments;Samples"
    },
    {
      "id": "FLM_BRAZILBASS",
      "name": "Brazil Bass",
      "link": "com.imageline.flstudiomobilehd.brazilbass",
      "category": "Bundle offer",
      "version": "3.6.0",
      "filename": "FLM3 Brazil Bass.zip",
      "free": false,
      "owned": false,
      "description": "35 Presets and 50 drum samples for punchy Brazil style bass music",
      "image": "https://support.image-line.com/images/product/flm-brazil-bass.png",
      "weight": "7",
      "demo": "https://support.image-line.com/innovaeditor/assets/plugins/audio/flm-brazil-bass-demo.mp3",
      "download": "https://streamermobile.image-line.com/inappv3/downloadProduct.php?hash=d32e9502c32600a8f0d45f0051c2ea79&version=&productname=com.imageline.flstudiomobilehd.brazilbass&time=1670783184",
      "formats": "DirectWave,Drum Samples",
      "genre": "",
      "instrument": "Bass;Synth;Drum",
      "plugin": "Instruments;Samples"
    }
  ],
  "userId": "4974507",
  "userAllowedDebugMode": 0
}
